[package]
name = "idi_risc0_methods"
version.workspace = true
edition.workspace = true

[package.metadata.risc0]
methods = ["idi-manifest", "idi-qtable"]

[dependencies]
risc0-zkvm = { workspace = true, default-features = false }

[build-dependencies]
risc0-build = { workspace = true }

